//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTUD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class InvoiceDetail : INotifyPropertyChanged
    {
        public int Id { get; set; }
        public Nullable<int> IdInvoice { get; set; }
        public Nullable<int> IdProduct { get; set; }
        private Nullable<int> _soLuong;
        public Nullable<double> GiaBan { get; set; }
        private Nullable<double> _tongTien;

        public void TinhTongGia()
        {
            TongTien = GiaBan * SoLuong;
        }

        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }

        public double? TongTien
        {
            get
            {
                return _tongTien;
            }

            set
            {
                _tongTien = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("TongTien"));
                }
            }
        }

        public int? SoLuong
        {
            get
            {
                return _soLuong;
            }

            set
            {
                _soLuong = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("SoLuong"));
                }
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
