//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTUD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }

        private string _name;
        private Nullable<float> _gia;
        private string _image;
        public int Id { get; set; }

        public string Name
        {
            get
            {
                return _name;
            }

            set
            {
                _name = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("Name"));
                }
            }
        }

        public Nullable<float> Gia
        {
            get
            {
                return _gia;
            }

            set
            {
                _gia = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("Gia"));
                }
            }
        }

        public string Image
        {
            get
            {
                return _image;
            }

            set
            {
                _image = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged.Invoke(this, new PropertyChangedEventArgs("Image"));
                }
            }
        }
        public void Equal(Product prd1)
        {
            this.Name = prd1.Name;
            this.Gia = prd1.Gia;
            this.Id = prd1.Id;
            //this.Image = prd1.Image;
        }


        public void ResetValue()
        {
            this.Name = "";
            this.Gia = 0;
            this.Id = 0;
            this.Image = "";
        }
        public event PropertyChangedEventHandler PropertyChanged;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
